// ---------------------------------------------------------------------
// Persistent storage of the tab groups list.
//
// A group is { created: <epoch ms>, tabs: [{ title, url }, ...] }.  The
// list is stored newest-first in chrome.storage.local (persistent, not
// synced across machines).
// ---------------------------------------------------------------------
const STORAGE_KEY = 'tabGroups';

async function getGroups() {
  const data = await chrome.storage.local.get(STORAGE_KEY);
  return data[STORAGE_KEY] || [];
}

async function saveGroups(groups) {
  await chrome.storage.local.set({ [STORAGE_KEY]: groups });
}

async function prependGroup(group) {
  const groups = await getGroups();
  groups.unshift(group);
  await saveGroups(groups);
  return groups;
}

// Removes the first group with a matching creation time.
async function removeGroup(created) {
  const groups = await getGroups();
  const idx = groups.findIndex((g) => g.created === created);
  if (idx !== -1) {
    groups.splice(idx, 1);
    await saveGroups(groups);
  }
  return groups;
}

// ---------------------------------------------------------------------
// Import / export text format.
//
// Each group is a "Time created:" line followed by one line per tab
// (URL, a tab, then an optional title), with a blank line between
// groups.  See spec_MVP.md.
// ---------------------------------------------------------------------
function pad2(n) {
  return String(n).padStart(2, '0');
}

// Formats an epoch-ms time as local "MM/DD/YYYY HH:MM:SS".
function formatCreated(ms) {
  const d = new Date(ms);
  return `${pad2(d.getMonth() + 1)}/${pad2(d.getDate())}/${d.getFullYear()} ` +
         `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
}

function serializeGroups(groups) {
  if (groups.length === 0) return '';
  const blocks = groups.map((group) => {
    const lines = [`Time created: ${formatCreated(group.created)}`];
    for (const tab of group.tabs) {
      lines.push(tab.title ? `${tab.url}\t${tab.title}` : tab.url);
    }
    return lines.join('\n');
  });
  return blocks.join('\n\n') + '\n';
}

// Parses the export text format back into groups.  Lenient, so a
// hand-edited file survives: a "Time created:" line starts a group; each
// following non-blank line is a tab (URL = first whitespace-delimited
// token, title = the rest); a blank line ends a group; an unparseable or
// missing timestamp falls back to the import time.  Groups with no tabs
// are dropped.
function parseGroups(text) {
  const importTime = Date.now();
  const groups = [];
  let current = null;

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();

    const header = line.match(/^Time created:(.*)$/);
    if (header) {
      const ms = Date.parse(header[1].trim());
      current = { created: Number.isNaN(ms) ? importTime : ms, tabs: [] };
      groups.push(current);
      continue;
    }

    if (line === '') {
      current = null; // a blank line ends the current group's tab list
      continue;
    }

    if (current) {
      const ws = line.search(/\s/);
      const url = ws === -1 ? line : line.slice(0, ws);
      const title = ws === -1 ? '' : line.slice(ws).trim();
      current.tabs.push({ title, url });
    }
  }

  return groups.filter((g) => g.tabs.length > 0);
}

// The list page path is machine-specific and stored in local-config.json,
// generated by setup.bat.  It is read fresh on each invocation so that
// running setup.bat takes effect without reloading the extension.
async function getListPageUrl() {
  try {
    const r = await fetch(chrome.runtime.getURL('local-config.json'));
    if (!r.ok) return null;
    const cfg = await r.json();
    return cfg.LIST_PAGE_URL || null;
  } catch {
    return null;
  }
}

chrome.commands.onCommand.addListener((command, tab) => {
  if (command === 'open-list') openList();
  // tab is the active tab when the shortcut fired; its window is the one
  // to archive.  getLastFocused (the fallback) can pick the wrong window
  // when several are open.
  if (command === 'archive-window') archiveWindow(tab?.windowId);
});

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'getGroups') {
    getGroups().then((groups) => sendResponse({ groups }));
    return true; // keep the message port open for the async response
  }
  if (message.action === 'exportText') {
    getGroups().then((groups) => sendResponse({ text: serializeGroups(groups) }));
    return true; // keep the message port open for the async response
  }
  if (message.action === 'importText') {
    (async () => {
      const groups = parseGroups(message.text);
      await saveGroups(groups);
      sendResponse({ groups });
    })();
    return true; // keep the message port open for the async response
  }
  if (message.action === 'recall') {
    recallGroup(message.created)
      .then(getGroups)
      .then((groups) => sendResponse({ groups }));
    return true; // keep the message port open for the async response
  }
  if (message.action === 'closeList') {
    if (sender.tab?.id != null) chrome.tabs.remove(sender.tab.id);
  }
});

// Recalls a group: opens a new focused window containing its tabs, in
// order, and removes the group from storage.  Best effort -- URLs that
// cannot be opened are skipped rather than aborting the recall.
async function recallGroup(created) {
  const groups = await getGroups();
  const group = groups.find((g) => g.created === created);
  if (!group) return;

  // Start from an empty window, then add each tab so one bad URL cannot
  // abort the whole window creation.
  const win = await chrome.windows.create({ focused: true });
  const placeholderTabId = win.tabs?.[0]?.id;

  let opened = 0;
  for (const tab of group.tabs) {
    try {
      await chrome.tabs.create({ windowId: win.id, url: tab.url, active: false });
      opened++;
    } catch {
      // Skip URLs that cannot be opened.
    }
  }

  // Drop the placeholder new-tab page once real tabs exist.
  if (opened > 0 && placeholderTabId != null) {
    try {
      await chrome.tabs.remove(placeholderTabId);
    } catch {}
  }

  await removeGroup(created);
}

async function openList() {
  const listPageUrl = await getListPageUrl();
  if (!listPageUrl) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  chrome.tabs.create({ url: listPageUrl });
}

// True for pages this extension itself owns -- its list page and any of
// its chrome-extension:// pages (e.g., setup-required.html) -- which
// should never be archived.
function isOwnUrl(url, listPageUrl) {
  if (!url) return false;
  if (url.startsWith(chrome.runtime.getURL(''))) return true;
  if (listPageUrl) {
    const base = url.split('#')[0].split('?')[0];
    if (base === listPageUrl) return true;
  }
  return false;
}

// Archives a window: records its tabs (in order, skipping this
// extension's own pages) as a new group, then closes the window.  If it
// is the only browser window, the list page is opened in a new window
// first so that Chrome does not quit.  windowId should be the window the
// user is in; it falls back to the last-focused window when omitted.
async function archiveWindow(windowId) {
  const win = windowId == null
    ? await chrome.windows.getLastFocused({ populate: true })
    : await chrome.windows.get(windowId, { populate: true });

  const listPageUrl = await getListPageUrl();
  const tabs = (win.tabs || [])
    .filter((t) => !isOwnUrl(t.url, listPageUrl))
    .map((t) => ({ title: t.title, url: t.url }));

  // A window of only our own pages has nothing to record, but is still
  // closed below for consistency.
  if (tabs.length > 0) {
    await prependGroup({ created: Date.now(), tabs });
  }

  const normalWindows = (await chrome.windows.getAll()).filter((w) => w.type === 'normal');
  if (normalWindows.length <= 1 && listPageUrl) {
    await chrome.windows.create({ url: listPageUrl });
  }

  await chrome.windows.remove(win.id);
}
