// ---------------------------------------------------------------------
// Persistent storage of the tab groups list.
//
// A group is { created: <epoch ms>, tabs: [{ title, url }, ...] }.  The
// list is stored newest-first in chrome.storage.local (persistent, not
// synced across machines).
// ---------------------------------------------------------------------
const STORAGE_KEY = 'tabGroups';

async function getGroups() {
  const data = await chrome.storage.local.get(STORAGE_KEY);
  return data[STORAGE_KEY] || [];
}

async function saveGroups(groups) {
  await chrome.storage.local.set({ [STORAGE_KEY]: groups });
}

async function prependGroup(group) {
  const groups = await getGroups();
  groups.unshift(group);
  await saveGroups(groups);
  return groups;
}

// Removes the first group with a matching creation time.
async function removeGroup(created) {
  const groups = await getGroups();
  const idx = groups.findIndex((g) => g.created === created);
  if (idx !== -1) {
    groups.splice(idx, 1);
    await saveGroups(groups);
  }
  return groups;
}

// The list page path is machine-specific and stored in local-config.json,
// generated by setup.bat.  It is read fresh on each invocation so that
// running setup.bat takes effect without reloading the extension.
async function getListPageUrl() {
  try {
    const r = await fetch(chrome.runtime.getURL('local-config.json'));
    if (!r.ok) return null;
    const cfg = await r.json();
    return cfg.LIST_PAGE_URL || null;
  } catch {
    return null;
  }
}

chrome.commands.onCommand.addListener((command) => {
  if (command === 'open-list') openList();
});

async function openList() {
  const listPageUrl = await getListPageUrl();
  if (!listPageUrl) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  chrome.tabs.create({ url: listPageUrl });
}
