// The list page path is machine-specific and stored in local-config.json,
// generated by setup.bat.  It is read fresh on each invocation so that
// running setup.bat takes effect without reloading the extension.
async function getListPageUrl() {
  try {
    const r = await fetch(chrome.runtime.getURL('local-config.json'));
    if (!r.ok) return null;
    const cfg = await r.json();
    return cfg.LIST_PAGE_URL || null;
  } catch {
    return null;
  }
}

chrome.commands.onCommand.addListener((command) => {
  if (command === 'open-list') openList();
});

async function openList() {
  const listPageUrl = await getListPageUrl();
  if (!listPageUrl) {
    chrome.tabs.create({ url: chrome.runtime.getURL('setup-required.html') });
    return;
  }
  chrome.tabs.create({ url: listPageUrl });
}
